### ISSUE TITLE
The New Status's

### ISSUE THREAD

**Issue by flamedfury** [katydecorah/read-action#148]
Hey Katy,

I love the `nowReading` status and explanation of how to use it. 

I've got some great ideas for revamping my bookshelf page on my website now.

One new feature that I thought would be great would be an `abandoned` status for books we've started but decided not to finish. It could take a "date abandoned" parameter.

Let me know what you think.

~fLaMEd

**Comment by katydecorah** [comment]
Love it!

**Comment by katydecorah** [comment]
@flamedfury I wanted to get your opinion. I can either:

1. Add the new `date-abandoned` field that will enable you to make the date you abandoned the book.
2. Refactor all date inputs into a single date field and then introduce a multiple choice option for the action:

## Option 1
```yaml
      date-started:
        description: Date you started the book (YYYY-MM-DD). Optional.
        type: string
      date-finished:
        description: Date you finished the book (YYYY-MM-DD). Optional.
        type: string
      date-abandoned:
        description: Date you abandoned the book (YYYY-MM-DD). Optional.
        type: string
````

I think the downside to option 1 is that now there are three inputs for a date-related field--a little noisy.

## Option 2

```yaml
      bookStatus:
        description: What is the status of the book? Required.
        required: true
        type: choice
        options:
          - "want to read"
          - "started"
          - "finished"
          - "abandoned"
      date:
        description: Date to record the status of the book (YYYY-MM-DD). Leave blank for today. Optional.
        type: string
```

I think the downside to option 2 is that you can no longer set multiple dates for the state of a book. I've personally never done this, I usually update the date as I go. Would you miss the ability to modify multiples dates (started date, finished date, want to read date) for a book at once?
